export default function Head(){
    return(
        <>
        <title>Create Next App</title>
        <meta content="width=device-width ,initial-scale=1" name="view" >
        </meta>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel='icon' href="/favicon.ico" />
        </>

    )
}